"""empty message

Revision ID: 363f56a60f33
Revises: 9045a1da987c
Create Date: 2021-06-02 21:42:18.044175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363f56a60f33'
down_revision = '9045a1da987c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'deleted')
    # ### end Alembic commands ###
