"""empty message

Revision ID: 9045a1da987c
Revises: b0edbbb07fc5
Create Date: 2021-06-02 20:52:57.723978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9045a1da987c'
down_revision = 'b0edbbb07fc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'deleted')
    # ### end Alembic commands ###
