"""empty message

Revision ID: b0edbbb07fc5
Revises: 977a4b8c47a7
Create Date: 2021-06-02 19:21:14.146064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0edbbb07fc5'
down_revision = '977a4b8c47a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('liked', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'liked')
    # ### end Alembic commands ###
